version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./tmp/mongodb:/data/db
    networks:
      - axon-compose-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - axon-compose-network
    links:
      - mongo
    depends_on:
      - mongo

  redis:
    image: redis:alpine
    container_name: redis_db
    ports:
      - 6379:6379
    volumes:
      - ./tmp/redis:/data/db
    restart: always
    networks:
      - axon-compose-network

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight
    ports:
      - '8001:8001'
    depends_on:
      - redis
    networks:
      - axon-compose-network

  axonserver:
    image: axoniq/axonserver
    container_name: axonserver
    hostname: axonserver
    volumes:
      - ./tmp/axonserver-data:/data
      - ./tmp/axonserver-events:/eventdata
      - ./tmp/axonserver-config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    depends_on:
      - mongo
    networks:
      - axon-compose-network

networks:
  axon-compose-network:
    driver: bridge