# spring
server:
  port: 9081

spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: order-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order-events

