# spring
server:
  port: 9080
spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: account-service-command
  data:
    mongodb:
      host: localhost
      port: 27017
      database: axon-events